// <auto-generated />
namespace RealEstateAspNetMVC5_Staj2021.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tablolarolusturdu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tablolarolusturdu));
        
        string IMigrationMetadata.Id
        {
            get { return "202108052140404_Tablolarolusturdu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
